# Generated by Django 5.1.3 on 2024-11-11 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User

def set_user_for_participants(apps, schema_editor):
    Participant = apps.get_model('reviews', 'Participant')
    for participant in Participant.objects.all():
        user, created = User.objects.get_or_create(username=participant.uid)
        participant.user = user
        participant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_participant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_user_for_participants),
    ]
